### PR TITLE
Improving performance by parsing flow output once

### PR DESCRIPTION
**Pull request by gabriel-laet**
Here is a proposal of how to improve performance. I couldn't think in another implementation other than adding a plugin to handle Flow process. There are still some work to do (write tests, docs, etc). cc @torifat 
## Changes
- Added `flowStatus` function to handle `flow` process. Using `spawn` instead of `execFile`
  to handle larger outputs returned by Flow
- Added `FlowtypePlugin`, responsible for handling Flow output parsing
  and reporting resources errors
- Changed loader to use method injected by `FlowtypePlugin`

### CODE REVIEW

**Comment by torifat** [comment]
It seems good to me 👍 Will try to merge as soon as I can.

**Comment by gabriel-laet** [comment]
@torifat Added `failOnError` option and updated `README.md`, let me know what do you think

**Review by torifat — APPROVED** [review]

**Comment by torifat** [comment]
@gabriel-laet Awesome, thanks 😄 Sorry, It's holiday here in my country so it took some time to respond.

**Comment by gabriel-laet** [comment]
@torifat cool! let me know when you publish a new version 😃

**Comment by torifat** [comment]
Sure 👍

**Pull request merged**
